version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./reactfrontend
      dockerfile: Dockerfile
    ports:
      - "3000:5173"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
